[General]
AlwaysEnablePreviewZoom=false
FileParameterDefaultPath=/home/redd
FolderParameterDefaultValue=/home/redd
LogosAreVisible=true
OutputMessageMode=0
PreviewTimeout=16
SelectedFilter=e5bbb4803c98109ba7d3f4fc35ce8fd1

[Config]
ExpandedFolders=<b>Details</b>, <b>Repair</b>
FilterSources=${GMIC_PATH}/.gmic, ${HOME}/.gmic
FilterTranslation=false
HighDPIEnabled=false
MainWindowMaximized=false
MainWindowPosition=@Point(2181 147)
MainWindowRect=@Rect(0 0 1013 570)
NativeColorDialogs=false
NativeFileDialogs=false
NotifyIfStartupUpdateFails=true
OfficialFilterSource=EnabledWithUpdates
PanelSize0=193
PanelSize1=424
PanelSize2=366
ParamsVerticalSplitterSizeBottom=75
ParamsVerticalSplitterSizeTop=426
PreviewEnabled=true
PreviewPosition=Right
RefreshInternetUpdate=true
ScreenGeometries="(1920,0,1536,864)"
UpdatesPeriodicityValue=2147483647

[LastExecution]
ExitedNormally=true
HostApplicationID=1
gmic_version=331
host_krita-plugin\Arguments="75,2,4,100,8,1,16,0,50,50"
host_krita-plugin\Command=fx_equalize_local_histograms
host_krita-plugin\FilterHash=e5bbb4803c98109ba7d3f4fc35ce8fd1
host_krita-plugin\FilterPath=/Details/Equalize Local Histograms
host_krita-plugin\GmicStatusString=
host_krita-plugin\InputMode=1
host_krita-plugin\OutputMode=0
