#!/bin/zsh

#function compsec {
  insecure_dirs=( ${(f@):-"$(compaudit 2>/dev/null)"} )
  # If no such directories exist, get us out of here.
  [[ -z "${insecure_dirs}" ]] && return
  # List ownership and permissions of all insecure directories.
  print "Insecure completion-dependent directories detected:"
  lsd -ld "${(@)insecure_dirs}"
#}
