#   ╔═══════════════  https://github.com/dropdeadredd/.runthedots.git  ═════════════════╗
#   ║  ·▄▄▄▄  ▄▄▄         ▄▄▄· ·▄▄▄▄  ▄▄▄ . ▄▄▄· ·▄▄▄▄   ▄▄▄  ▄▄▄ .·▄▄▄▄  ·▄▄▄▄  .▄▄ ·  ║
#   ║ ██▪ ██ ▀▄ █·▪     ▐█ ▄█  ██▪ ██ ▀▄.▀·▐█ ▀█ ██▪ ██  ▀▄ █·▀▄.▀·██▪ ██ ██▪ ██ ▐█ ▀.  ║
#   ║ ▐█· ▐█▌▐▀▀▄  ▄█▀▄  ██▀·  ▐█· ▐█▌▐▀▀▪▄▄█▀▀█ ▐█· ▐█▌ ▐▀▀▄ ▐▀▀▪▄▐█· ▐█▌▐█· ▐█▌▄▀▀▀█▄ ║
#   ║ ██. ██ ▐█•█▌▐█▌.▐▌▐█▪·•  ██. ██ ▐█▄▄▌▐█ ▪▐▌██. ██  ▐█•█▌▐█▄▄▌██. ██ ██. ██ ▐█▄▪▐█ ║
#   ║ ▀▀▀▀▀• .▀  ▀ ▀█▄▀▪.▀     ▀▀▀▀▀•  ▀▀▀  ▀  ▀ ▀▀▀▀▀•  .▀  ▀ ▀▀▀ ▀▀▀▀▀• ▀▀▀▀▀•  ▀▀▀▀  ║
#   ╚══════════════════════════════════  .runthedots  ══════════════════════════════════╝

right_format = """
[](fg:#98BB6C)\
$python\
[](bg:#98BB6C fg:#FFA066)\
$git_commit\
$git_branch\
$git_status\
[](bg:#FFA066 fg:#252535 )\
$memory_usage\
[](bg:#252535 fg:#DCD7BA)\
$time\
[▓▒░](fg:#DCD7BA)\
"""
format = """
[░▒▓](fg:#252535)\
$directory\
[](fg:#252535)\
\n$character"""


add_newline = false

[character]
success_symbol = '[ 󰏰](#DCD7BA)'
error_symbol = '[ 󰏰](#BD3B3B)'

[line_break]
disabled = true

[directory]
style = "fg:#DCD7BA bg:#252535"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
".runthedots" = "󰈙 "
"Downloads" = " "
"Pictures" = " "

[memory_usage]
symbol = "󰘚"
threshold = -1
style = "bg:#252535 "
format = '[[ ($symbol Mem:$ram_pct) ($symbol Swap:$swap_pct) ](fg:#DCD7BA bg:#252535 )]($style)'
disabled = false

[git_branch]
symbol = ""
style = "bg:#FFA066"
format = '[[ $symbol $branch ](fg:#252535 bg:#FFA066)]($style)'

[git_status]
style = "bg:#FFA066"
format = '[[( $all_status $ahead_behind )](fg:#252535 bg:#FFA066)]($style)'
ignore_submodules = true

[python]
symbol = ""
style = "bg:#98BB6C"
format = '[[ $symbol ($virtualenv) ](fg:#252535 bg:#98BB6C)]($style)'

[time]
disabled = false
time_format = "%A %-I:%M%p" # Weekday 12Hour:Minute Format
style = "bg:#DCD7BA"
format = '[[ $time ](fg:#252535 bg:#DCD7BA)]($style)'
